/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'finance' : IDL.Null,
  'social' : IDL.Null,
  'hobby' : IDL.Null,
  'miscellaneous' : IDL.Null,
  'education' : IDL.Null,
  'work' : IDL.Null,
  'exercise' : IDL.Null,
  'health' : IDL.Null,
});
export const HabitId = IDL.Text;
export const UserProfile = IDL.Record({ 'displayName' : IDL.Text });
export const Date = IDL.Text;
export const Completion = IDL.Record({
  'date' : Date,
  'completed' : IDL.Bool,
  'habitId' : HabitId,
});
export const Habit = IDL.Record({
  'id' : HabitId,
  'name' : IDL.Text,
  'createdAt' : Date,
  'color' : IDL.Text,
  'category' : Category,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createHabit' : IDL.Func([IDL.Text, IDL.Text, Category], [HabitId], []),
  'deleteHabit' : IDL.Func([HabitId], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDisplayName' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getHabitCompletions' : IDL.Func([HabitId], [IDL.Vec(Completion)], ['query']),
  'getHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markCompletion' : IDL.Func([HabitId, Date, IDL.Bool], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setDisplayName' : IDL.Func([IDL.Text], [], []),
  'updateHabit' : IDL.Func(
      [HabitId, IDL.Text, IDL.Text, Category],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'finance' : IDL.Null,
    'social' : IDL.Null,
    'hobby' : IDL.Null,
    'miscellaneous' : IDL.Null,
    'education' : IDL.Null,
    'work' : IDL.Null,
    'exercise' : IDL.Null,
    'health' : IDL.Null,
  });
  const HabitId = IDL.Text;
  const UserProfile = IDL.Record({ 'displayName' : IDL.Text });
  const Date = IDL.Text;
  const Completion = IDL.Record({
    'date' : Date,
    'completed' : IDL.Bool,
    'habitId' : HabitId,
  });
  const Habit = IDL.Record({
    'id' : HabitId,
    'name' : IDL.Text,
    'createdAt' : Date,
    'color' : IDL.Text,
    'category' : Category,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createHabit' : IDL.Func([IDL.Text, IDL.Text, Category], [HabitId], []),
    'deleteHabit' : IDL.Func([HabitId], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDisplayName' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getHabitCompletions' : IDL.Func(
        [HabitId],
        [IDL.Vec(Completion)],
        ['query'],
      ),
    'getHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markCompletion' : IDL.Func([HabitId, Date, IDL.Bool], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setDisplayName' : IDL.Func([IDL.Text], [], []),
    'updateHabit' : IDL.Func(
        [HabitId, IDL.Text, IDL.Text, Category],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };