/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Completion {
  'date' : Date,
  'completed' : boolean,
  'habitId' : HabitId,
}
export type Date = string;
export interface Habit {
  'id' : HabitId,
  'name' : string,
  'createdAt' : Date,
  'color' : string,
}
export type HabitId = string;
export interface UserProfile { 'displayName' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createHabit' : ActorMethod<[string, string], HabitId>,
  'deleteHabit' : ActorMethod<[HabitId], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDisplayName' : ActorMethod<[], [] | [string]>,
  'getHabitCompletions' : ActorMethod<[HabitId], Array<Completion>>,
  'getHabits' : ActorMethod<[], Array<Habit>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markCompletion' : ActorMethod<[HabitId, Date, boolean], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setDisplayName' : ActorMethod<[string], undefined>,
  'updateHabit' : ActorMethod<[HabitId, string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];